[build.env]
passthrough = [
    "PROTOC",
    "PKG_CONFIG_ALLOW_CROSS",
    "PKG_CONFIG_PATH",
]

[target.armv7-linux-androideabi]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install -y protobuf-compiler",
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf", 
    "apt-get update",
    "apt-get install -y protobuf-compiler",
    "apt-get install -y libdbus-1-dev:armhf pkg-config",
]