[build.env]
passthrough = [
    "PROTOC",
    "PKG_CONFIG_ALLOW_CROSS",
    "PATH",
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y protobuf-compiler",
    "apt-get install -y libdbus-1-dev:arm64 pkg-config",
]

[target.armv7-linux-androideabi]
pre-build = [
    "apt-get update", 
    "apt-get install -y protobuf-compiler",
    "which protoc || echo 'protoc not found in PATH'",
    "protoc --version || echo 'protoc version check failed'",
]
[target.armv7-linux-androideabi.env]
PROTOC = "/usr/bin/protoc"

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install -y protobuf-compiler",
    "apt-get install -y libdbus-1-dev:armhf pkg-config",
    "which protoc || echo 'protoc not found in PATH'",
    "protoc --version || echo 'protoc version check failed'",
]
[target.armv7-unknown-linux-gnueabihf.env]
PROTOC = "/usr/bin/protoc"