[package]
name = "metamesh-cli"
version = "0.1.0"
edition = "2021"
description = "MetaMesh command-line interface"

[[bin]]
name = "metamesh"
path = "src/main.rs"

[dependencies]
metamesh-identity = { path = "../common/identity" }
clap = { workspace = true }