[package]
name = "metamesh-transport"
version = "0.1.0"
edition = "2021"

[features]
default = ["ble"]
ble = ["btleplug"]

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
bitflags = { workspace = true }
btleplug = { workspace = true, optional = true }