name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          pkg-config \
          libdbus-1-dev \
          libbluetooth-dev \
          protobuf-compiler
    
    - name: Check formatting
      run: cargo fmt --all -- --check
      continue-on-error: true
    
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      continue-on-error: true
    
    - name: Run tests
      run: cargo test --all-features